import { ICustomer } from "@/lib/types/crm";

export const INITIAL_CRM_CUSTOMERS: ICustomer[] = [
  {
    id: "crm-101",
    businessName: "Apex Mobile Repairs Inc",
    contactName: "Marcus Vance",
    customerType: "Repair Shop",
    email: "orders@apexrepairs.com",
    phone: "+1 (555) 234-5678",
    address: {
      street: "148 West 34th St, Suite 402",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
    },
    outstandingDebt: 12400.0,
    walletBalance: 2500.0,
    creditLimit: 50000.0,
    notes: "High-volume repair chain specializing in iPhone & Galaxy screen replacements. Tier 1 priority.",
    tags: ["High Volume", "VIP Repair", "Net 30"],
    avatarColor: "bg-indigo-600",
    status: "Active",
    totalSpent: 128500.0,
    totalOrders: 64,
    communications: [
      {
        id: "comm-1",
        type: "Call",
        subject: "Credit Limit Increase Discussion",
        content: "Spoke with Marcus regarding extending credit line to $50k. Approved based on 100% on-time payment track record.",
        loggedBy: "Alex Rivers",
        date: "2026-07-28T14:30:00Z",
      },
      {
        id: "comm-2",
        type: "Email",
        subject: "Bulk Order Discount Confirmation",
        content: "Confirmed 17.1% volume discount on iPhone 16 Pro Max OLED assemblies for monthly orders over 20 units.",
        loggedBy: "Sarah Jenkins",
        date: "2026-07-20T09:15:00Z",
      },
      {
        id: "comm-3",
        type: "Note",
        subject: "RMA Inspection Pending",
        content: "Customer submitted RMA-401 for iPhone 15 Pro Max display digitizer issue. Tech team currently inspecting.",
        loggedBy: "System API",
        date: "2026-07-29T11:00:00Z",
      },
    ],
    timeline: [
      {
        id: "tl-1",
        type: "payment",
        title: "Payment Received",
        description: "Cleared Stripe payment for Invoice #INV-2026-9401",
        amount: 2480.0,
        badge: "Stripe",
        date: "2026-07-30T20:18:00Z",
      },
      {
        id: "tl-2",
        type: "order",
        title: "Sales Order Placed",
        description: "Order #SO-2026-9401 created for 40 parts (Screens & Batteries)",
        amount: 2480.0,
        badge: "Wholesale",
        date: "2026-07-30T20:15:00Z",
      },
      {
        id: "tl-3",
        type: "warranty",
        title: "Warranty Claim Filed",
        description: "RMA-401 filed for iPhone 15 Pro Max OLED Assembly (Digitizer Unresponsive)",
        badge: "RMA-401",
        date: "2026-07-29T10:45:00Z",
      },
      {
        id: "tl-4",
        type: "wallet",
        title: "Wallet Top-up",
        description: "Prepaid deposit added via Bank Transfer to account wallet",
        amount: 2500.0,
        badge: "Credit Balance",
        date: "2026-07-25T16:00:00Z",
      },
      {
        id: "tl-5",
        type: "credit",
        title: "Credit Limit Updated",
        description: "Revolving line of credit limit increased from $35,000 to $50,000",
        amount: 50000.0,
        badge: "Credit Line",
        date: "2026-07-28T14:30:00Z",
      },
    ],
    returnsHistory: [
      {
        id: "ret-1",
        rmaNumber: "RMA-401",
        date: "2026-07-29",
        partName: "iPhone 15 Pro Max OLED Assembly",
        reason: "Touch digitizer unresponsive on bottom right corner",
        status: "Pending",
        amount: 320.0,
        quantity: 1,
      },
      {
        id: "ret-2",
        rmaNumber: "RMA-380",
        date: "2026-06-15",
        partName: "Galaxy S23 Ultra Battery Pack",
        reason: "Defective flex cable connector pin",
        status: "Approved",
        amount: 85.0,
        quantity: 2,
      },
    ],
  },
  {
    id: "crm-102",
    businessName: "Global Tech Distributors Ltd",
    contactName: "Elena Rostova",
    customerType: "Distributor",
    email: "procurement@globalelectronics.com",
    phone: "+1 (555) 777-8899",
    address: {
      street: "890 Industrial Pkwy, Bldg B",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      country: "USA",
    },
    outstandingDebt: 45420.0,
    walletBalance: 10000.0,
    creditLimit: 100000.0,
    notes: "Regional master distributor supplying Midwest repair networks. Requires Net 60 terms.",
    tags: ["Distributor", "Bulk Logistics", "Net 60"],
    avatarColor: "bg-purple-600",
    status: "Active",
    totalSpent: 215000.0,
    totalOrders: 42,
    communications: [
      {
        id: "comm-4",
        type: "Meeting",
        subject: "Q3 Bulk Procurement Agreement",
        content: "Met with Elena to finalize bulk purchasing agreement for 500+ iPhone 16 screens per quarter.",
        loggedBy: "Alex Rivers",
        date: "2026-07-25T11:00:00Z",
      },
      {
        id: "comm-5",
        type: "Email",
        subject: "Partial Wire Transfer Clearance",
        content: "Received ACH confirmation for $4,000 partial payment on INV-2026-9399.",
        loggedBy: "Accounting Dept",
        date: "2026-07-30T18:30:00Z",
      },
    ],
    timeline: [
      {
        id: "tl-6",
        type: "payment",
        title: "Partial Payment Received",
        description: "ACH Wire Transfer #TX-90123 processed for Invoice #INV-2026-9399",
        amount: 4000.0,
        badge: "Bank Wire",
        date: "2026-07-30T18:30:00Z",
      },
      {
        id: "tl-7",
        type: "order",
        title: "Wholesale Bulk Shipment Placed",
        description: "Invoice #INV-2026-9399 issued for 45 units total",
        amount: 9420.0,
        badge: "Net 60",
        date: "2026-07-30T18:22:00Z",
      },
    ],
    returnsHistory: [
      {
        id: "ret-3",
        rmaNumber: "RMA-392",
        date: "2026-07-10",
        partName: "iPhone 14 Pro Triple Camera Sensor Unit",
        reason: "Shipping package crushed in transit by carrier",
        status: "Approved",
        amount: 725.0,
        quantity: 5,
      },
    ],
  },
  {
    id: "crm-103",
    businessName: "iFixFast Depot Brooklyn",
    contactName: "David Kim",
    customerType: "Retail",
    email: "billing@ifixfast.io",
    phone: "+1 (555) 987-6543",
    address: {
      street: "312 Atlantic Ave",
      city: "Brooklyn",
      state: "NY",
      zipCode: "11201",
      country: "USA",
    },
    outstandingDebt: 0.0,
    walletBalance: 850.0,
    creditLimit: 25000.0,
    notes: "Walk-in retail storefront and quick counter repair facility.",
    tags: ["Retail Store", "Counter Pickup", "Same-Day"],
    avatarColor: "bg-emerald-600",
    status: "Active",
    totalSpent: 48900.0,
    totalOrders: 38,
    communications: [
      {
        id: "comm-6",
        type: "Call",
        subject: "Counter Pickup Notification",
        content: "Notified David that rear glass assembly order INV-2026-9400 is ready for NYC Hub pickup.",
        loggedBy: "Sarah Connor",
        date: "2026-07-30T19:45:00Z",
      },
    ],
    timeline: [
      {
        id: "tl-8",
        type: "payment",
        title: "Terminal Card Payment Paid",
        description: "Credit card payment authorized at POS Terminal NY",
        amount: 890.5,
        badge: "Paid in Full",
        date: "2026-07-30T19:42:00Z",
      },
      {
        id: "tl-9",
        type: "warranty",
        title: "Warranty RMA Approved",
        description: "RMA-400 Galaxy S24 Ultra Battery Pack thermal cycle failure approved for full refund",
        amount: 42.0,
        badge: "Approved",
        date: "2026-07-28T14:00:00Z",
      },
    ],
    returnsHistory: [
      {
        id: "ret-4",
        rmaNumber: "RMA-400",
        date: "2026-07-28",
        partName: "Galaxy S24 Ultra Battery Pack",
        reason: "Fails high-rate thermal cycle test",
        status: "Approved",
        amount: 42.0,
        quantity: 1,
      },
    ],
  },
  {
    id: "crm-104",
    businessName: "TechMaster Warehouse LA",
    contactName: "Carlos Mendez",
    customerType: "Distributor",
    email: "logistics@techmasterla.com",
    phone: "+1 (555) 111-2233",
    address: {
      street: "4500 Olympic Blvd",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90015",
      country: "USA",
    },
    outstandingDebt: 0.0,
    walletBalance: 15000.0,
    creditLimit: 75000.0,
    notes: "West Coast wholesale partner serving Southern California tech centers.",
    tags: ["Distributor", "West Coast", "Prepaid"],
    avatarColor: "bg-blue-600",
    status: "Active",
    totalSpent: 84750.0,
    totalOrders: 29,
    communications: [
      {
        id: "comm-7",
        type: "SMS",
        subject: "West Coast Depot Dispatch Status",
        content: "Automated alert sent for shipment #INV-2026-9397 out for delivery via LA Hub.",
        loggedBy: "System API",
        date: "2026-07-28T15:00:00Z",
      },
    ],
    timeline: [
      {
        id: "tl-10",
        type: "payment",
        title: "Credit Line Payment Cleared",
        description: "Paid Invoice #INV-2026-9397 using revolving line credit balance",
        amount: 4850.75,
        badge: "Cleared",
        date: "2026-07-30T14:15:00Z",
      },
    ],
    returnsHistory: [],
  },
  {
    id: "crm-105",
    businessName: "QuickFix Cellular Queens",
    contactName: "Samira Patel",
    customerType: "Repair Shop",
    email: "info@quickfixqueens.com",
    phone: "+1 (555) 444-3322",
    address: {
      street: "72-15 Jamaica Ave",
      city: "Queens",
      state: "NY",
      zipCode: "11421",
      country: "USA",
    },
    outstandingDebt: 410.0,
    walletBalance: 0.0,
    creditLimit: 10000.0,
    notes: "Neighborhood repair store. Currently has 1 overdue invoice under automated notice.",
    tags: ["Repair Shop", "Overdue Notice", "Due on Receipt"],
    avatarColor: "bg-amber-600",
    status: "On Hold",
    totalSpent: 16400.0,
    totalOrders: 19,
    communications: [
      {
        id: "comm-8",
        type: "Email",
        subject: "Overdue Invoice Payment Reminder",
        content: "Automated payment reminder dispatched for overdue Invoice #INV-2026-9398 ($410.00). Account placed on temporary hold.",
        loggedBy: "System API",
        date: "2026-07-15T08:00:00Z",
      },
    ],
    timeline: [
      {
        id: "tl-11",
        type: "warranty",
        title: "RMA Rejected",
        description: "RMA-399 rejected due to physical flex pin bending post installation",
        badge: "Rejected",
        date: "2026-07-26T09:30:00Z",
      },
      {
        id: "tl-12",
        type: "order",
        title: "Overdue Invoice Flagged",
        description: "Invoice #INV-2026-9398 past 20 days due date",
        amount: 410.0,
        badge: "Overdue",
        date: "2026-07-10T00:00:00Z",
      },
    ],
    returnsHistory: [
      {
        id: "ret-5",
        rmaNumber: "RMA-399",
        date: "2026-07-26",
        partName: "Pixel 8 Pro Charging Port Flex Cable",
        reason: "Physical pin bending post install (User mishandling)",
        status: "Rejected",
        amount: 25.0,
        quantity: 1,
      },
    ],
  },
  {
    id: "crm-106",
    businessName: "NextGen Wireless Retail",
    contactName: "Jason Miller",
    customerType: "Retail",
    email: "procurement@nextgenwireless.com",
    phone: "+1 (555) 333-9988",
    address: {
      street: "500 Market St",
      city: "Philadelphia",
      state: "PA",
      zipCode: "19106",
      country: "USA",
    },
    outstandingDebt: 1200.0,
    walletBalance: 500.0,
    creditLimit: 20000.0,
    notes: "Multi-location retail accessory and screen protector vendor.",
    tags: ["Retail Chain", "Accessories", "Net 15"],
    avatarColor: "bg-teal-600",
    status: "Active",
    totalSpent: 32400.0,
    totalOrders: 21,
    communications: [
      {
        id: "comm-9",
        type: "Call",
        subject: "Stock Availability Inquiry",
        content: "Jason called asking about bulk availability for Pixel 8 Pro USB-C Flex Cables and TrueTone EEPROM chips.",
        loggedBy: "Alex Rivers",
        date: "2026-07-27T15:45:00Z",
      },
    ],
    timeline: [
      {
        id: "tl-13",
        type: "wallet",
        title: "Store Credit Applied",
        description: "Prepaid wallet funds deposited for future accessory shipments",
        amount: 500.0,
        badge: "Wallet",
        date: "2026-07-22T12:00:00Z",
      },
    ],
    returnsHistory: [],
  },
];
