import { IInventoryItem, IInventoryMovement } from "@/lib/types/inventory";

export const INITIAL_INVENTORY_ITEMS: Omit<IInventoryItem, "_id" | "createdAt" | "updatedAt">[] = [
  {
    sku: "SCR-IP15P-OLED-BLK",
    product: "iPhone 15 Pro OLED Display Assembly with Touch Digitizer",
    brand: "Apple",
    phoneModel: "iPhone 15 Pro",
    category: "Screen Replacement",
    quality: "OEM_ORIGINAL",
    supplier: "Foxconn Direct Wholesale",
    warehouse: "Main Hub - New York",
    shelf: "A1-S2-B04",
    quantity: 142,
    reserved: 12,
    available: 130,
    cost: 165.00,
    sellingPrice: 249.99,
    status: "IN_STOCK",
    reorderPoint: 25,
    barcode: "885909483012",
    lastMovedAt: "2026-07-28T14:30:00Z",
  },
  {
    sku: "BAT-SAM-S24U-5000",
    product: "Samsung Galaxy S24 Ultra Replacement Battery (5000mAh)",
    brand: "Samsung",
    phoneModel: "Galaxy S24 Ultra",
    category: "Battery",
    quality: "SERVICE_PACK",
    supplier: "Shenzhen Parts Co.",
    warehouse: "Main Hub - New York",
    shelf: "B3-S1-B12",
    quantity: 85,
    reserved: 5,
    available: 80,
    cost: 22.50,
    sellingPrice: 49.99,
    status: "IN_STOCK",
    reorderPoint: 20,
    barcode: "880609123456",
    lastMovedAt: "2026-07-29T09:15:00Z",
  },
  {
    sku: "CHG-PIX8P-FLEX",
    product: "Google Pixel 8 Pro USB-C Charging Port Flex Cable",
    brand: "Google",
    phoneModel: "Pixel 8 Pro",
    category: "Charging Port",
    quality: "PREMIUM_AFTERMARKET",
    supplier: "Sunsky Logistics",
    warehouse: "West Coast Depot - LA",
    shelf: "C2-S4-B01",
    quantity: 18,
    reserved: 4,
    available: 14,
    cost: 8.20,
    sellingPrice: 24.50,
    status: "LOW_STOCK",
    reorderPoint: 20,
    barcode: "840019283746",
    lastMovedAt: "2026-07-25T11:45:00Z",
  },
  {
    sku: "CAM-IP14P-MAIN",
    product: "iPhone 14 Pro 48MP Rear Camera Module Original",
    brand: "Apple",
    phoneModel: "iPhone 14 Pro",
    category: "Camera Module",
    quality: "OEM_ORIGINAL",
    supplier: "Foxconn Direct Wholesale",
    warehouse: "Main Hub - New York",
    shelf: "A2-S1-B08",
    quantity: 64,
    reserved: 8,
    available: 56,
    cost: 89.00,
    sellingPrice: 149.00,
    status: "IN_STOCK",
    reorderPoint: 15,
    barcode: "885909982144",
    lastMovedAt: "2026-07-27T16:20:00Z",
  },
  {
    sku: "GLS-SAM-S23P-GRY",
    product: "Samsung Galaxy S23 Plus Back Glass Door - Phantom Black",
    brand: "Samsung",
    phoneModel: "Galaxy S23 Plus",
    category: "Back Glass",
    quality: "REFURBISHED_A",
    supplier: "Shenzhen Parts Co.",
    warehouse: "Central Hub - Texas",
    shelf: "D1-S3-B02",
    quantity: 0,
    reserved: 0,
    available: 0,
    cost: 12.00,
    sellingPrice: 29.99,
    status: "OUT_OF_STOCK",
    reorderPoint: 10,
    barcode: "880609876543",
    lastMovedAt: "2026-06-12T10:00:00Z",
  },
  {
    sku: "SCR-IP13-OLED-INCELL",
    product: "iPhone 13 Incell LCD Screen Assembly Replacement",
    brand: "Apple",
    phoneModel: "iPhone 13",
    category: "Screen Replacement",
    quality: "PREMIUM_AFTERMARKET",
    supplier: "Sunsky Logistics",
    warehouse: "West Coast Depot - LA",
    shelf: "A3-S1-B10",
    quantity: 210,
    reserved: 15,
    available: 195,
    cost: 45.00,
    sellingPrice: 79.99,
    status: "IN_STOCK",
    reorderPoint: 30,
    barcode: "885909776512",
    lastMovedAt: "2026-07-30T08:10:00Z",
  },
  {
    sku: "BAT-1P-11PRO-3000",
    product: "iPhone 11 Pro Battery Replacement 3046mAh Zero Cycle",
    brand: "Apple",
    phoneModel: "iPhone 11 Pro",
    category: "Battery",
    quality: "PREMIUM_AFTERMARKET",
    supplier: "OEM Global Parts",
    warehouse: "EU Logistics - Rotterdam",
    shelf: "E2-S2-B09",
    quantity: 5,
    reserved: 0,
    available: 5,
    cost: 14.50,
    sellingPrice: 32.00,
    status: "DEAD_STOCK",
    reorderPoint: 15,
    barcode: "885909112233",
    lastMovedAt: "2025-11-14T09:00:00Z",
  },
  {
    sku: "FLX-XIA-13T-PWR",
    product: "Xiaomi 13T Pro Power & Volume Button Flex Cable",
    brand: "Xiaomi",
    phoneModel: "Xiaomi 13T Pro",
    category: "Flex Cable",
    quality: "OEM_ORIGINAL",
    supplier: "Shenzhen Parts Co.",
    warehouse: "Central Hub - Texas",
    shelf: "C1-S1-B05",
    quantity: 95,
    reserved: 2,
    available: 93,
    cost: 3.50,
    sellingPrice: 12.99,
    status: "IN_STOCK",
    reorderPoint: 15,
    barcode: "693417771234",
    lastMovedAt: "2026-07-20T13:40:00Z",
  },
  {
    sku: "IC-IP14-PWR-U3000",
    product: "iPhone 14 Power Management IC Chip PMIC U3000",
    brand: "Apple",
    phoneModel: "iPhone 14",
    category: "Motherboard IC",
    quality: "OEM_ORIGINAL",
    supplier: "OEM Global Parts",
    warehouse: "Main Hub - New York",
    shelf: "S1-S1-B01",
    quantity: 340,
    reserved: 20,
    available: 320,
    cost: 4.80,
    sellingPrice: 15.00,
    status: "IN_STOCK",
    reorderPoint: 50,
    barcode: "885909334455",
    lastMovedAt: "2026-07-29T17:00:00Z",
  },
  {
    sku: "SCR-SAM-ZFLIP5-INT",
    product: "Samsung Galaxy Z Flip 5 Inner Folding OLED Screen Service Pack",
    brand: "Samsung",
    phoneModel: "Galaxy Z Flip 5",
    category: "Screen Replacement",
    quality: "SERVICE_PACK",
    supplier: "Foxconn Direct Wholesale",
    warehouse: "Main Hub - New York",
    shelf: "A4-S2-B01",
    quantity: 12,
    reserved: 1,
    available: 11,
    cost: 210.00,
    sellingPrice: 329.99,
    status: "LOW_STOCK",
    reorderPoint: 15,
    barcode: "880609543210",
    lastMovedAt: "2026-07-26T10:15:00Z",
  },
  {
    sku: "BAT-PIX7A-4385",
    product: "Google Pixel 7a Battery Replacement 4385mAh",
    brand: "Google",
    phoneModel: "Pixel 7a",
    category: "Battery",
    quality: "OEM_ORIGINAL",
    supplier: "Sunsky Logistics",
    warehouse: "West Coast Depot - LA",
    shelf: "B1-S3-B07",
    quantity: 78,
    reserved: 6,
    available: 72,
    cost: 18.00,
    sellingPrice: 39.99,
    status: "IN_STOCK",
    reorderPoint: 20,
    barcode: "840019554433",
    lastMovedAt: "2026-07-28T15:20:00Z",
  },
  {
    sku: "HOU-1P-15PM-TIT-NAT",
    product: "iPhone 15 Pro Max Full Chassis Housing Assembly - Natural Titanium",
    brand: "Apple",
    phoneModel: "iPhone 15 Pro Max",
    category: "Back Glass",
    quality: "OEM_ORIGINAL",
    supplier: "Foxconn Direct Wholesale",
    warehouse: "Central Hub - Texas",
    shelf: "D2-S1-B11",
    quantity: 28,
    reserved: 3,
    available: 25,
    cost: 145.00,
    sellingPrice: 229.00,
    status: "IN_STOCK",
    reorderPoint: 10,
    barcode: "885909009988",
    lastMovedAt: "2026-07-29T12:00:00Z",
  }
];

export const INITIAL_MOVEMENTS: Record<string, Omit<IInventoryMovement, "_id" | "createdAt">[]> = {
  "SCR-IP15P-OLED-BLK": [
    {
      inventoryItemId: "item-1",
      sku: "SCR-IP15P-OLED-BLK",
      productName: "iPhone 15 Pro OLED Display Assembly",
      type: "RECEIPT",
      quantityChange: 100,
      previousQuantity: 42,
      newQuantity: 142,
      toWarehouse: "Main Hub - New York",
      toShelf: "A1-S2-B04",
      reason: "PO-2026-8842 Goods Received from Foxconn",
      performedBy: "Alex Rivers (Inventory Mgr)",
    },
    {
      inventoryItemId: "item-1",
      sku: "SCR-IP15P-OLED-BLK",
      productName: "iPhone 15 Pro OLED Display Assembly",
      type: "TRANSFER",
      quantityChange: -15,
      previousQuantity: 57,
      newQuantity: 42,
      fromWarehouse: "Main Hub - New York",
      toWarehouse: "West Coast Depot - LA",
      fromShelf: "A1-S2-B04",
      toShelf: "A2-S1-B01",
      reason: "Inter-warehouse stock rebalance transfer #TR-9921",
      performedBy: "Elena Rostova",
    },
    {
      inventoryItemId: "item-1",
      sku: "SCR-IP15P-OLED-BLK",
      productName: "iPhone 15 Pro OLED Display Assembly",
      type: "SALE",
      quantityChange: -10,
      previousQuantity: 67,
      newQuantity: 57,
      reason: "Wholesale Fulfillment Order #SO-7741 (TechFix Pro Shops)",
      performedBy: "System Dispatcher",
    },
    {
      inventoryItemId: "item-1",
      sku: "SCR-IP15P-OLED-BLK",
      productName: "iPhone 15 Pro OLED Display Assembly",
      type: "INITIAL_IMPORT",
      quantityChange: 67,
      previousQuantity: 0,
      newQuantity: 67,
      reason: "Initial ERP Migration Import",
      performedBy: "System Admin",
    }
  ]
};
